theme: minima
title: Kore Wa Kore's Blog
author: 
description: Kore wa place where I put my thoughts and insights. Thanks for taking a look! 
Yellow star divider by @pixopix on Tumblr.
baseurl: /blog
url: https://korewa-kore.github.io

# Social links (optional)
github_username: KoreWa-Kore
twitter_username: Kore_wa_Kore
substack_username: korewakore

# Minima theme settings
minima:
header_pages:
  - about.md
  - support.md
