theme: minima
title: Kore Wa Kore's Blog
author: Kore
description: Kore wa place where I put my thoughts and insights. Thanks for taking a look!

# Social links (optional)
github_username: KoreWa-Kore
twitter_username: Kore_wa_Kore

# Minima theme settings
minima:
header_pages:
  - about.md
  - support.md
