theme: minima
title: Kore wa blog. 
author: 
description: Yellow star divider by @pixopix on Tumblr. 
/n Thank you for taking a look!
baseurl: /blog
url: https://korewa-kore.github.io

# Social links (optional)
github_username: KoreWa-Kore
twitter_username: Kore_wa_Kore
substack_username: korewakore

# Minima theme settings
minima:
header_pages:
  - about.md
  - support.md
